import * as mongoose from 'mongoose'

export const LaptopSchema= new mongoose.Schema({
        id:String,
        name: String,
        url: String,
        image: String,
        price:Number,
        brand:String,
        cpu:String,
        gpu:String,
        display_size:String,
        display_size_txt:String,
        display_resolution:String,
        panel_name:String,
        panel_type:String,
        display_features:Array,
        is_glossy_matte:String,
        storage_ssd:String,
        storage_hdd:String,
        ram:Number,
        ram_txt:String,
        weight:Number,
        weight_txt:String,
        suitable_for:Array,
        pop_searches:Array,
        show_our:Array,
        review_url:String,
        brand_logo:String,
        profiles_url:String,
})
export interface Laptop {
    name: string,
    url: string,
    image: string,
    price:Number,
    brand:string,
    cpu:string,
    gpu:string,
    display_size:string,
    display_size_txt:string,
    display_resolution:string,
    panel_name:string,
    panel_type:string,
    display_features:any,
    is_glossy_matte:string,
    storage_ssd:string,
    storage_hdd:string,
    ram:Number,
    ram_txt:string,
    weight:Number,
    weight_txt:string,
    suitable_for:any,
    pop_searches:any,
    show_our:any,
    review_url:string,
    brand_logo:string,
    profiles_url:string,
}
